# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecondHandCar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1388, 818)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 560, 471, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayoutButton = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayoutButton.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutButton.setObjectName("verticalLayoutButton")
        self.btnShowResults = QtWidgets.QPushButton(self.layoutWidget)
        self.btnShowResults.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnShowResults.setStyleSheet("QPushButton{\n"
"    border-color:  #6affe7;\n"
"    border-width: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #57fff1;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #0eff93;\n"
"    color: black;\n"
"}")
        self.btnShowResults.setObjectName("btnShowResults")
        self.verticalLayoutButton.addWidget(self.btnShowResults)
        self.btnClear = QtWidgets.QPushButton(self.layoutWidget)
        self.btnClear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClear.setStyleSheet("QPushButton{\n"
"    border-color:  #6affe7;\n"
"    border-width: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #57fff1;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #0eff93;\n"
"    color: black;\n"
"}")
        self.btnClear.setObjectName("btnClear")
        self.verticalLayoutButton.addWidget(self.btnClear)
        self.btnShowAllResults = QtWidgets.QPushButton(self.layoutWidget)
        self.btnShowAllResults.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnShowAllResults.setStyleSheet("QPushButton{\n"
"    border-color:  #6affe7;\n"
"    border-width: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #57fff1;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #0eff93;\n"
"    color: black;\n"
"}")
        self.btnShowAllResults.setObjectName("btnShowAllResults")
        self.verticalLayoutButton.addWidget(self.btnShowAllResults)
        self.btnDownload = QtWidgets.QPushButton(self.layoutWidget)
        self.btnDownload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDownload.setStyleSheet("QPushButton{\n"
"    border-color:  #6affe7;\n"
"    border-width: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #57fff1;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #0eff93;\n"
"    color: black;\n"
"}")
        self.btnDownload.setObjectName("btnDownload")
        self.verticalLayoutButton.addWidget(self.btnDownload)
        self.frameFilter = QtWidgets.QFrame(self.centralwidget)
        self.frameFilter.setEnabled(True)
        self.frameFilter.setGeometry(QtCore.QRect(0, 10, 471, 541))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frameFilter.setFont(font)
        self.frameFilter.setAutoFillBackground(False)
        self.frameFilter.setStyleSheet("border-style: solid;\n"
"border-width: 5px;\n"
"border-color: #6affe7;\n"
"background-color: #FFFAFA;")
        self.frameFilter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFilter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFilter.setLineWidth(2)
        self.frameFilter.setObjectName("frameFilter")
        self.gridLayout = QtWidgets.QGridLayout(self.frameFilter)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayoutFilter = QtWidgets.QVBoxLayout()
        self.verticalLayoutFilter.setObjectName("verticalLayoutFilter")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frameFilter)
        self.label_2.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cmbBrand = QtWidgets.QComboBox(self.frameFilter)
        self.cmbBrand.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cmbBrand.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.cmbBrand.setObjectName("cmbBrand")
        self.horizontalLayout.addWidget(self.cmbBrand)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frameFilter)
        self.label_3.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.cmbModel = QtWidgets.QComboBox(self.frameFilter)
        self.cmbModel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cmbModel.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.cmbModel.setObjectName("cmbModel")
        self.horizontalLayout_2.addWidget(self.cmbModel)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frameFilter)
        self.label_4.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.cmbEngineType = QtWidgets.QComboBox(self.frameFilter)
        self.cmbEngineType.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cmbEngineType.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.cmbEngineType.setObjectName("cmbEngineType")
        self.horizontalLayout_3.addWidget(self.cmbEngineType)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frameFilter)
        self.label.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.cmbYear = QtWidgets.QComboBox(self.frameFilter)
        self.cmbYear.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.cmbYear.setObjectName("cmbYear")
        self.horizontalLayout_4.addWidget(self.cmbYear)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.frameFilter)
        self.label_10.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.label_8 = QtWidgets.QLabel(self.frameFilter)
        self.label_8.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lneMax_2 = QtWidgets.QLineEdit(self.frameFilter)
        self.lneMax_2.setStyleSheet("QLineEdit{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.lneMax_2.setText("")
        self.lneMax_2.setObjectName("lneMax_2")
        self.horizontalLayout_5.addWidget(self.lneMax_2)
        self.label_11 = QtWidgets.QLabel(self.frameFilter)
        self.label_11.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.lneMax = QtWidgets.QLineEdit(self.frameFilter)
        self.lneMax.setStyleSheet("QLineEdit{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.lneMax.setText("")
        self.lneMax.setObjectName("lneMax")
        self.horizontalLayout_5.addWidget(self.lneMax)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frameFilter)
        self.label_6.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.cmbFuelType = QtWidgets.QComboBox(self.frameFilter)
        self.cmbFuelType.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cmbFuelType.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.cmbFuelType.setObjectName("cmbFuelType")
        self.horizontalLayout_8.addWidget(self.cmbFuelType)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frameFilter)
        self.label_7.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.cmbGearType = QtWidgets.QComboBox(self.frameFilter)
        self.cmbGearType.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cmbGearType.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.cmbGearType.setObjectName("cmbGearType")
        self.horizontalLayout_6.addWidget(self.cmbGearType)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.frameFilter)
        self.label_12.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.cmbWarranty = QtWidgets.QComboBox(self.frameFilter)
        self.cmbWarranty.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cmbWarranty.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.cmbWarranty.setObjectName("cmbWarranty")
        self.horizontalLayout_11.addWidget(self.cmbWarranty)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frameFilter)
        self.label_5.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.label_13 = QtWidgets.QLabel(self.frameFilter)
        self.label_13.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.lneMin_2 = QtWidgets.QLineEdit(self.frameFilter)
        self.lneMin_2.setStyleSheet("QLineEdit{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.lneMin_2.setText("")
        self.lneMin_2.setObjectName("lneMin_2")
        self.horizontalLayout_7.addWidget(self.lneMin_2)
        self.label_9 = QtWidgets.QLabel(self.frameFilter)
        self.label_9.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.lneMin = QtWidgets.QLineEdit(self.frameFilter)
        self.lneMin.setStyleSheet("QLineEdit{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.lneMin.setText("")
        self.lneMin.setObjectName("lneMin")
        self.horizontalLayout_7.addWidget(self.lneMin)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayoutFilter, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(500, 10, 831, 541))
        self.tableWidget.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"border-color: #6affe7;\n"
"background-color: #FFFAFA;")
        self.tableWidget.setRowCount(99)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.QPlanText_Terminal = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.QPlanText_Terminal.setGeometry(QtCore.QRect(653, 566, 681, 191))
        self.QPlanText_Terminal.setObjectName("QPlanText_Terminal")
        self.btnPullData = QtWidgets.QPushButton(self.centralwidget)
        self.btnPullData.setGeometry(QtCore.QRect(520, 570, 93, 28))
        self.btnPullData.setObjectName("btnPullData")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(490, 610, 71, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(570, 610, 55, 16))
        self.label_15.setObjectName("label_15")
        self.PullDataYearFrom = QtWidgets.QLineEdit(self.centralwidget)
        self.PullDataYearFrom.setGeometry(QtCore.QRect(490, 640, 61, 22))
        self.PullDataYearFrom.setObjectName("PullDataYearFrom")
        self.PullDataYearTo = QtWidgets.QLineEdit(self.centralwidget)
        self.PullDataYearTo.setGeometry(QtCore.QRect(570, 640, 61, 22))
        self.PullDataYearTo.setObjectName("PullDataYearTo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1388, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnShowResults.setText(_translate("MainWindow", "SHOW RESULTS"))
        self.btnClear.setText(_translate("MainWindow", "CLEAR"))
        self.btnShowAllResults.setText(_translate("MainWindow", "SHOW ALL RESULTS"))
        self.btnDownload.setText(_translate("MainWindow", "DOWNLOAD"))
        self.label_2.setText(_translate("MainWindow", "Brand:"))
        self.label_3.setText(_translate("MainWindow", "Model:"))
        self.label_4.setText(_translate("MainWindow", "Engine Type:"))
        self.label.setText(_translate("MainWindow", "Year:"))
        self.label_10.setText(_translate("MainWindow", "Km:"))
        self.label_8.setText(_translate("MainWindow", "Min:"))
        self.lneMax_2.setInputMask(_translate("MainWindow", "999999999999"))
        self.label_11.setText(_translate("MainWindow", "Max:"))
        self.lneMax.setInputMask(_translate("MainWindow", "999999999999"))
        self.label_6.setText(_translate("MainWindow", "Fuel Type"))
        self.label_7.setText(_translate("MainWindow", "Gear Type:"))
        self.label_12.setText(_translate("MainWindow", "Warranty Status:"))
        self.label_5.setText(_translate("MainWindow", "Price:"))
        self.label_13.setText(_translate("MainWindow", "Min:"))
        self.lneMin_2.setInputMask(_translate("MainWindow", "999999999999"))
        self.label_9.setText(_translate("MainWindow", "Max:"))
        self.lneMin.setInputMask(_translate("MainWindow", "999999999999"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "BRAND"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MODEL"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ENGİNE TYPE"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "YEAR"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "KM"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "FUEL TYPE"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "GEAR TYPE"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "PRİCE"))
        self.btnPullData.setText(_translate("MainWindow", "Pull Data"))
        self.label_14.setText(_translate("MainWindow", "Page From"))
        self.label_15.setText(_translate("MainWindow", "   To"))
        self.PullDataYearFrom.setInputMask(_translate("MainWindow", "9999"))
        self.PullDataYearTo.setInputMask(_translate("MainWindow", "9999"))
