# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondHandCar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1402, 583)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color:#151a1e;\n"
"}\n"
"QCalendar {\n"
"    background-color: #151a1e;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"    background-color: #222b2e;\n"
"    color: #d3dae3;\n"
"}\n"
"QPlainTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"    background-color: #222b2e;\n"
"    color: #d3dae3;\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #1c1f1f;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #2c2f2f;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"    background-color: #222b2e;\n"
"    color: #d3dae3;\n"
"}\n"
"QLabel {\n"
"    color: #d3dae3;\n"
"}\n"
"QLCDNumber {\n"
"    color: #4d9b87;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: #d3dae3;\n"
"    border-radius: 10px;\n"
"    border-color: transparent;\n"
"    border-style: solid;\n"
"    background-color: #52595d;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #214037    ;\n"
"    border-radius: 10px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #151a1e;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #d3dae3;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"    background-color: #151a1e;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background-color: #252a2e;\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu {\n"
"    background-color: #151a1e;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #252a2e;\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item {\n"
"    color: #d3dae3;\n"
"    background-color: #151a1e;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: #050a0e;\n"
"        background-color: #1e282c;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"}\n"
"QTabBar::tab:first {\n"
"    border-style: solid;\n"
"    border-left-width:1px;\n"
"    border-right-width:0px;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:0px;\n"
"    border-top-color: #050a0e;\n"
"    border-left-color: #050a0e;\n"
"    border-bottom-color: #050a0e;\n"
"    border-top-left-radius: 4px;\n"
"    color: #d3dae3;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QTabBar::tab:last {\n"
"    border-style: solid;\n"
"    border-top-width:1px;\n"
"    border-left-width:1px;\n"
"    border-right-width:1px;\n"
"    border-bottom-width:0px;\n"
"    border-color: #050a0e;\n"
"    border-top-right-radius: 4px;\n"
"    color: #d3dae3;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:0px;\n"
"    border-left-width:1px;\n"
"    border-top-color: #050a0e;\n"
"    border-left-color: #050a0e;\n"
"    border-bottom-color: #050a0e;\n"
"    color: #d3dae3;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"    border-bottom-width:0px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: #050a0e;\n"
"    border-left-color: #050a0e;\n"
"    border-bottom-color: #050a0e;\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: #1e282c;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:first:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"      border-bottom-width:0px;\n"
"      border-top-width:1px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: #050a0e;\n"
"    border-left-color: #050a0e;\n"
"    border-bottom-color: #050a0e;\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: #1e282c;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #4fa08b;\n"
"    color: #000000;\n"
"    background-color: qradialgradient(cx:0.4, cy:0.4, radius: 1.5,fx:0, fy:0, stop:0 #1e282c, stop:0.3 #1e282c, stop:0.4 #4fa08b, stop:0.5 #1e282c, stop:1 #1e282c);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #4fa08b;\n"
"    color: #000000;\n"
"}\n"
"QRadioButton {\n"
"    color: #d3dae3;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #4fa08b;\n"
"    color: #a9b7c6;\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:0.4,fx:0.5, fy:0.5, stop:0 #4fa08b, stop:1 #1e282c);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #4fa08b;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QTimeEdit {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QDateTimeEdit {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QDateEdit {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QFontComboBox {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QComboBox {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"\n"
"QDial {\n"
"    background: #16a085;\n"
"}\n"
"\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #222b2e;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#222b2e;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background-color: #52595d;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background-color: #52595d;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #1a2224;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: #1a2224;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: #52595d;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: #52595d;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: #15433a;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background-color: #15433a;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #52595d;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #58a492;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #52595d;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #58a492;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 4px;\n"
"   border-bottom-right-radius: 4px;\n"
"   background: #15433a;\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 4px;\n"
"   border-bottom-right-radius: 4px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 4px;\n"
"   border-bottom-right-radius: 4px;\n"
"   background: #15433a;\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 4px;\n"
"   border-bottom-right-radius: 4px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 4px;\n"
"   border-bottom-left-radius: 4px;\n"
"   background: #15433a;\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 4px;\n"
"   border-bottom-left-radius: 4px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 4px;\n"
"   border-top-right-radius: 4px;\n"
"   background: #15433a;\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 4px;\n"
"   border-top-right-radius: 4px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"   background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"   background: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(460, 40, 931, 461))
        self.tableWidget.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"border-color: #6affe7;\n"
"background-color: #FFFAFA;")
        self.tableWidget.setRowCount(99)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 128, 128))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.frameFilter = QtWidgets.QFrame(self.centralwidget)
        self.frameFilter.setGeometry(QtCore.QRect(3, 49, 421, 256))
        self.frameFilter.setStyleSheet("border-style: solid;\n"
"border-width: 5px;\n"
"border-color: #6affe7;\n"
"background-color: #FFFAFA;")
        self.frameFilter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFilter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFilter.setObjectName("frameFilter")
        self.gridLayout = QtWidgets.QGridLayout(self.frameFilter)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayoutFilter = QtWidgets.QVBoxLayout()
        self.verticalLayoutFilter.setObjectName("verticalLayoutFilter")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frameFilter)
        self.label.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.frameFilter)
        self.spinBox.setStyleSheet("QSpinBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.spinBox.setMinimum(2010)
        self.spinBox.setMaximum(2024)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frameFilter)
        self.label_2.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.frameFilter)
        self.comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frameFilter)
        self.label_3.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox_3 = QtWidgets.QComboBox(self.frameFilter)
        self.comboBox_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_3.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_3.addWidget(self.comboBox_3)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frameFilter)
        self.label_4.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.frameFilter)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.frameFilter)
        self.label_5.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(self.frameFilter)
        self.label_8.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frameFilter)
        self.lineEdit_8.setStyleSheet("QLineEdit{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_8.addWidget(self.lineEdit_8)
        self.label_9 = QtWidgets.QLabel(self.frameFilter)
        self.label_9.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frameFilter)
        self.lineEdit_9.setStyleSheet("QLineEdit{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_8.addWidget(self.lineEdit_9)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frameFilter)
        self.label_6.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox_4 = QtWidgets.QComboBox(self.frameFilter)
        self.comboBox_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_4.setStyleSheet("QComboBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_4)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frameFilter)
        self.label_7.setStyleSheet("color: black;\n"
"border-color: black;\n"
"background-color: #20B2AA;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.checkBox = QtWidgets.QCheckBox(self.frameFilter)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setStyleSheet("QCheckBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QCheckBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.checkBox.setAutoExclusive(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_7.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frameFilter)
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_2.setStyleSheet("QCheckBox{\n"
"    border-color:black;\n"
"    color: black;\n"
"    background-color: #008080;\n"
"}\n"
"QCheckBox:hover{\n"
"    background-color: #57fff1;\n"
"}")
        self.checkBox_2.setAutoExclusive(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_7.addWidget(self.checkBox_2)
        self.verticalLayoutFilter.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayoutFilter, 0, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 320, 411, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayoutButton = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayoutButton.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutButton.setObjectName("verticalLayoutButton")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-color:  #6affe7;\n"
"    border-width: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #57fff1;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #0eff93;\n"
"    color: black;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutButton.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-color:  #6affe7;\n"
"    border-width: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #57fff1;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #0eff93;\n"
"    color: black;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutButton.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border-color:  #6affe7;\n"
"    border-width: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #57fff1;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #0eff93;\n"
"    color: black;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayoutButton.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border-color:  #6affe7;\n"
"    border-width: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #57fff1;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #0eff93;\n"
"    color: black;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayoutButton.addWidget(self.pushButton_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1402, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MODEL YEAR"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "BRAND"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MILEAGE"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MODEL"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PRİCE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "CITY"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "CRASH REPORT"))
        self.label.setText(_translate("MainWindow", "Model Year:"))
        self.label_2.setText(_translate("MainWindow", "Brand:"))
        self.label_3.setText(_translate("MainWindow", "Mileage:"))
        self.label_4.setText(_translate("MainWindow", "Model:"))
        self.label_5.setText(_translate("MainWindow", "Price:"))
        self.label_8.setText(_translate("MainWindow", "Min:"))
        self.lineEdit_8.setInputMask(_translate("MainWindow", "999999999999"))
        self.label_9.setText(_translate("MainWindow", "Max:"))
        self.lineEdit_9.setInputMask(_translate("MainWindow", "999999999999"))
        self.label_6.setText(_translate("MainWindow", "City:"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "ADANA "))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "ADIYAMAN"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "AFYON"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "AĞRI"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "AMASYA"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "ANKARA"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "ANTALYA"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "ARTVİN"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "AYDIN"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "BALIKESİR"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "BİLECİK"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "BİNGÖL"))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "BİTLİS"))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "BOLU"))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "BURDUR"))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "BURSA"))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "ÇANAKKALE"))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "ÇANKIRI"))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "ÇORUM"))
        self.comboBox_4.setItemText(20, _translate("MainWindow", "DENİZLİ"))
        self.comboBox_4.setItemText(21, _translate("MainWindow", "DİYARBAKIR"))
        self.comboBox_4.setItemText(22, _translate("MainWindow", "EDİRNE"))
        self.comboBox_4.setItemText(23, _translate("MainWindow", "ELAZIĞ"))
        self.comboBox_4.setItemText(24, _translate("MainWindow", "ERZİNCAN"))
        self.comboBox_4.setItemText(25, _translate("MainWindow", "ERZURUM"))
        self.comboBox_4.setItemText(26, _translate("MainWindow", "ESKİŞEHİR"))
        self.comboBox_4.setItemText(27, _translate("MainWindow", "GAZİANTEP"))
        self.comboBox_4.setItemText(28, _translate("MainWindow", "GİRESUN"))
        self.comboBox_4.setItemText(29, _translate("MainWindow", "GÜMÜŞHANE"))
        self.comboBox_4.setItemText(30, _translate("MainWindow", "HAKKARİ"))
        self.comboBox_4.setItemText(31, _translate("MainWindow", "HATAY"))
        self.comboBox_4.setItemText(32, _translate("MainWindow", "ISPARTA"))
        self.comboBox_4.setItemText(33, _translate("MainWindow", "MERSİN"))
        self.comboBox_4.setItemText(34, _translate("MainWindow", "İSTANBUL"))
        self.comboBox_4.setItemText(35, _translate("MainWindow", "İZMİR"))
        self.comboBox_4.setItemText(36, _translate("MainWindow", "KARS"))
        self.comboBox_4.setItemText(37, _translate("MainWindow", "KASTAMONU"))
        self.comboBox_4.setItemText(38, _translate("MainWindow", "KAYSERİ"))
        self.comboBox_4.setItemText(39, _translate("MainWindow", "KIRKLARELİ"))
        self.comboBox_4.setItemText(40, _translate("MainWindow", "KIRŞEHİR"))
        self.comboBox_4.setItemText(41, _translate("MainWindow", "KOCAELİ"))
        self.comboBox_4.setItemText(42, _translate("MainWindow", "KONYA"))
        self.comboBox_4.setItemText(43, _translate("MainWindow", "KÜTAHYA"))
        self.comboBox_4.setItemText(44, _translate("MainWindow", "MALATYA"))
        self.comboBox_4.setItemText(45, _translate("MainWindow", "MANİSA"))
        self.comboBox_4.setItemText(46, _translate("MainWindow", "KAHRAMANMARAŞ"))
        self.comboBox_4.setItemText(47, _translate("MainWindow", "MARDİN"))
        self.comboBox_4.setItemText(48, _translate("MainWindow", "MUĞLA"))
        self.comboBox_4.setItemText(49, _translate("MainWindow", "MUŞ"))
        self.comboBox_4.setItemText(50, _translate("MainWindow", "NEVŞEHİR"))
        self.comboBox_4.setItemText(51, _translate("MainWindow", "NİĞDE"))
        self.comboBox_4.setItemText(52, _translate("MainWindow", "ORDU"))
        self.comboBox_4.setItemText(53, _translate("MainWindow", "RİZE"))
        self.comboBox_4.setItemText(54, _translate("MainWindow", "SAKARYA"))
        self.comboBox_4.setItemText(55, _translate("MainWindow", "SAMSUN"))
        self.comboBox_4.setItemText(56, _translate("MainWindow", "SİİRT"))
        self.comboBox_4.setItemText(57, _translate("MainWindow", "SİNOP"))
        self.comboBox_4.setItemText(58, _translate("MainWindow", "SİVAS"))
        self.comboBox_4.setItemText(59, _translate("MainWindow", "TEKİRDAĞ"))
        self.comboBox_4.setItemText(60, _translate("MainWindow", "TOKAT"))
        self.comboBox_4.setItemText(61, _translate("MainWindow", "TRABZON"))
        self.comboBox_4.setItemText(62, _translate("MainWindow", "TUNCELİ"))
        self.comboBox_4.setItemText(63, _translate("MainWindow", "ŞANLIURFA"))
        self.comboBox_4.setItemText(64, _translate("MainWindow", "UŞAK"))
        self.comboBox_4.setItemText(65, _translate("MainWindow", "ZONGULDAK"))
        self.comboBox_4.setItemText(66, _translate("MainWindow", "AKSARAY"))
        self.comboBox_4.setItemText(67, _translate("MainWindow", "BAYBURT"))
        self.comboBox_4.setItemText(68, _translate("MainWindow", "KARAMAN"))
        self.comboBox_4.setItemText(69, _translate("MainWindow", "KIRIKKALE"))
        self.comboBox_4.setItemText(70, _translate("MainWindow", "BATMAN"))
        self.comboBox_4.setItemText(71, _translate("MainWindow", "ŞIRNAK"))
        self.comboBox_4.setItemText(72, _translate("MainWindow", "BARTIN"))
        self.comboBox_4.setItemText(73, _translate("MainWindow", "ARDAHAN"))
        self.comboBox_4.setItemText(74, _translate("MainWindow", "IĞDIR"))
        self.comboBox_4.setItemText(75, _translate("MainWindow", "YALOVA"))
        self.comboBox_4.setItemText(76, _translate("MainWindow", "KARABÜK"))
        self.comboBox_4.setItemText(77, _translate("MainWindow", "KİLİS"))
        self.comboBox_4.setItemText(78, _translate("MainWindow", "OSMANİYE"))
        self.comboBox_4.setItemText(79, _translate("MainWindow", "DÜZCE"))
        self.label_7.setText(_translate("MainWindow", "Crash Report:"))
        self.checkBox.setText(_translate("MainWindow", "EXIST"))
        self.checkBox_2.setText(_translate("MainWindow", "NON-EXIST "))
        self.pushButton.setText(_translate("MainWindow", "SHOW RESULTS"))
        self.pushButton_2.setText(_translate("MainWindow", "CLEAR"))
        self.pushButton_3.setText(_translate("MainWindow", "SHOW ALL RESULTS"))
        self.pushButton_4.setText(_translate("MainWindow", "DOWNLOAD"))

